[build]
builder = "dockerfile"
dockerfilePath = "my-medlm-api-app/Dockerfile"
buildContext = "my-medlm-api-app"

[deploy]
startCommand = "hypercorn main:app --bind [::]:8000"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
